### PR TITLE
Migrate to Adaptive Card 1.3 Version

### PR DESCRIPTION
**Pull request by Sakthivel-Ramasamy**
Code changes commit for webexpythonsdk's Adaptive Card 1.1 to 1.3 version upgrade. Changes involve code files restructuring inline with Adaptive Card's official documentation (https://adaptivecards.io/explorer/).

### CODE REVIEW

**Comment by Sakthivel-Ramasamy** [comment]
set_if_not_none() function from utils.py has been removed as I did not find any usage in the entire SDK!

**Review by Joezanini — CHANGES_REQUESTED** [review]
The code was formatted well and passed the linter test. but when I went to test I ran into a Syntax Error. 

The output indicated that the test run failed due to a SyntaxError in the file WebexPythonSDK/src/webexpythonsdk/models/cards/utils.py at line 58. The specific error message is SyntaxError: '(' was never closed, which means there is an unmatched opening parenthesis ( in the code.

To fix this, you need to locate the unmatched parenthesis in utils.py and ensure that every opening parenthesis has a corresponding closing parenthesis ).

**Comment by Sakthivel-Ramasamy** [comment]
It is surprising. I tried the same and simulated an error to reach that particular piece of code, but it worked correctly. Can you please share the adaptive card code that you've used that led to this error?

**Comment by Joezanini** [comment]
Now I am getting a SyntaxError: f-string: expecting '}'. This is for src/webexpythonsdk/models/cards/utils.py Line 61. I think it has to do with the quotation mark placement.

**Comment by Sakthivel-Ramasamy** [comment]
Code commit for #243

**Pull request merged**
